FROM python:{{ python_version }}-buster

WORKDIR /app
RUN apt-get update -y && apt-get install make -y

COPY . .
RUN pip install --upgrade pip
RUN pip install flit==3.8.0
RUN export PIP_INDEX_URL=$PIP_INDEX_URL
RUN FLIT_ROOT_INSTALL=1 flit install

ENTRYPOINT TEST_RUN="TRUE" pytest -s tests
